# Generated by Django 2.2.5 on 2019-11-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RRuleSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField(default=1)),
                ('starts_on', models.DateTimeField()),
                ('inter', models.IntegerField(default=1)),
                ('count', models.IntegerField(null=True)),
                ('ends_on', models.DateTimeField(null=True)),
                ('bysetpos', models.IntegerField(null=True)),
                ('bymonth', models.IntegerField(null=True)),
                ('bymonthday', models.IntegerField(null=True)),
                ('byyearday', models.IntegerField(null=True)),
                ('byeaster', models.IntegerField(null=True)),
                ('byweekno', models.IntegerField(null=True)),
                ('byweekday', models.IntegerField(null=True)),
                ('byhour', models.IntegerField(null=True)),
                ('byminute', models.IntegerField(null=True)),
                ('bysecond', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'RRuleSchedule',
                'verbose_name_plural': 'RRuleSchedules',
                'ordering': ['frequency', 'starts_on', 'ends_on'],
            },
        ),
    ]
