# Generated by Django 2.2.5 on 2019-11-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_customeperiodictask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rruleschedule',
            name='starts_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
